### ISSUE TITLE
There are duplicate Media Queries in the bundled css file

### ISSUE THREAD

**Issue by theonlyengineer** [jsdcommunity/static-website#10]
![image](https://user-images.githubusercontent.com/66003926/117121179-e653cb80-adb1-11eb-8461-d4e097aa462c.png)
This issue can be solved by using Postcss in the project. It might also be helpful to automatically add vendor-prefixed properties to the css file that's being generated by Webpack.

**Comment by mohdmusthafa** [comment]
@nizar-dev01 I will take a look into this.
